# Generated by Django 5.2 on 2025-04-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_vendor_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Contact',
            new_name='contact',
        ),
    ]
