# Generated by Django 5.2 on 2025-04-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rental_duration_rental_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='drop_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pick_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
