# Generated by Django 5.2 on 2025-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rental_drop_off_location_rental_drop_off_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_days',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_rate',
        ),
        migrations.AddField(
            model_name='rental',
            name='notes1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='notes2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='notes3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
