# Generated by Django 5.2 on 2025-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_remove_rental_notes_remove_rental_rental_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='category',
            field=models.CharField(choices=[('main_equipment', 'main_equipment'), ('special_equipment', 'special_equipment'), ('office_equipment', 'office_equipment'), ('set_equipment', 'set_equipment'), ('misc_equipment', 'misc_equipment')], default='choose category', max_length=100),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('ROS', 'ROS'), ('Drop Load', 'Drop Load')], default='choose rental type', max_length=100),
        ),
    ]
