# Generated by Django 5.2 on 2025-04-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Resquestor',
            new_name='resquestor',
        ),
    ]
