# Generated by Django 5.2 on 2025-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_service_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requestor',
            field=models.CharField(default='requestor', max_length=100),
        ),
    ]
