# Generated by Django 5.2 on 2025-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_service_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
