
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),
    path('update_user/', views.update_user, name='update_user'),
    path('password/', views.update_password, name='password'),
    path('user_list/', views.user_list, name='user_list'),
    path('production_form', views.ProductionInfoFormView.as_view(), name='production_form'),
    path('vendor_form/', views.VendorFormView.as_view(), name='vendor_form'),
    path('department_form/', views.DepartmentFormView.as_view(), name='department_form'),
    path('rental_form/', views.RentalFormView.as_view(), name='rental_form'),
    #path('vendor_list/', views.VendorListView.as_view(), name='vendor_list'),
    path('vendor_detail/<int:pk>/', views.VendorDetailView.as_view(), name='vendor_detail'),
    path('vendor_update/<int:pk>/', views.VendorUpdateView.as_view(), name='vendor_update'),
    path('vendor_delete/<int:pk>/', views.VendorDeleteView.as_view(), name='vendor_delete'),
    path('vendor_list/', views.vendor_list, name='vendor_list'),
    path('rental_form', views.RentalFormView.as_view(), name='rental_form'),
    path('vendor_category/', views.VendorCategoryFormView.as_view(), name='vendor_category'),
    path('rental_list/', views.RentalListView.as_view(), name='rental_list'),
    path('rental_detail/<int:pk>/', views.RentalDetailView.as_view(), name='rental_detail'),
    path('rental_update/<int:pk>/', views.RentalUpdateView.as_view(), name='rental_update'),
    path('rental_delete/<int:pk>/', views.RentalDeleteView.as_view(), name='rental_delete'),
    path('rental_detai_pdfl/<int:pk>/', views.rental_detail_pdf, name='rental_detail_pdf'),
    path('rental_detail_txt/<int:pk>/', views.rental_detail_txt, name='rental_detail_txt'),
    path('vendor_text', views.vendor_text, name='vendor_text'),
    path('vendor_csv', views.vendor_csv, name='vendor_csv'),
    path('vendor_pdf', views.vendor_pdf, name='vendor_pdf'),
    path('main_equipment', views.main_equipment_list, name='main_equipment'),
    path('special_equipment', views.special_equipment_list, name='special_equipment'),
    path('set_equipment', views.set_equipment_list, name='set_equipment'),
    path('office_equipment', views.production_office_equipment_list, name='office_equipment'),
    path('misc_equipment', views.misc_equipment_list, name='misc_equipment'),
    path('service_list/', views.service_list, name='service_list'),
    path('rental_text/', views.rental_txt, name='rental_text'),
    path('rental_pdf/', views.rental_pdf, name='rental_pdf'),
    path('rental_csv/', views.rental_csv, name='rental_csv'),
    path('main_equipment_text/', views.main_equipment_txt, name='main_equipment_text'),
    path('main_equipment_csv/', views.main_equipment_csv, name='main_equipment_csv'),
    path('main_equipment_pdf/', views.main_equipment_pdf, name='main_equipment_pdf'),
    path('special_equipment/txt/', views.special_equipment_txt, name='special_equipment_txt'),
    path('special_equipment_csv/', views.special_equipment_csv, name='special_equipment_csv'),
    path('special_equipment_pdf/', views.special_equipment_pdf, name='special_equipment_pdf'),
    path('set_equipment_txt/', views.set_equipment_txt, name='set_equipment_txt'),
    path('set_equipment_csv/', views.set_equipment_csv, name='set_equipment_csv'),
    path('set_equipment_pdf/', views.set_equipment_pdf, name='set_equipment_pdf'),
    path('office_equipment_txt/', views.office_equipment_txt, name='office_equipment_txt'),
    path('office_equipment_csv/', views.office_equipment_csv, name='office_equipment_csv'),
    path('office_equipment_pdf/', views.office_equipment_pdf, name='office_equipment_pdf'),
    path('service_list/', views.service_list, name='service_list'),
    path('service_form/', views.ServiceFormView.as_view(), name='service_form'),
    path('service_detail/<int:pk>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('service_update/<int:pk>/', views.ServiceUpdateView.as_view(), name='service_update'),
    path('service_delete/<int:pk>/', views.ServiceDeleteView.as_view(), name='service_delete'),
    path('service_list_text/', views.service_list_txt, name='service_list_text'),
    path('service_list_csv/', views.service_list_csv, name='service_list_csv'),
    path('service_list_pdf/', views.service_list_pdf, name='service_list_pdf'),
    path('service_detail_text/<int:pk>/', views.service_detail_txt, name='service_detail_text'),
    path('service_detail_pdf/<int:pk>/', views.service_detail_pdf, name='service_detail_pdf'),
    # Seach section
    path('search_rentals/', views.SearchRentals.as_view(), name='search_rentals'),
    path('search_services/', views.SearchServices.as_view(), name='search_services'),
    path('search_vendors/', views.SearchVendors.as_view(), name='search_vendors'),



]