# Generated by Django 5.2 on 2025-04-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='department', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_company', models.CharField(default='company', max_length=100)),
                ('show_name', models.CharField(default='show', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='vendor', max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_item', models.CharField(default='item', max_length=100)),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('last_name', models.CharField(default='last', max_length=100)),
                ('title', models.CharField(default='title', max_length=100)),
                ('scene_info', models.CharField(blank=True, max_length=300, null=True)),
                ('start_rental_date', models.DateField()),
                ('end_rental_date', models.DateField()),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_days', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('addl_tax_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.department')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.production')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.vendor')),
            ],
        ),
    ]
