# Generated by Django 5.2 on 2025-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Contact',
            field=models.CharField(blank=True, default='contact', max_length=100, null=True),
        ),
    ]
