# Generated by Django 5.2 on 2025-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_vendor_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='COI_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
    ]
