# Generated by Django 5.2 on 2025-04-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_service_end_service_date_service_start_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.vendor'),
        ),
    ]
