# Generated by Django 5.2 on 2025-04-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_service_department_service_notes1_service_notes2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.production'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
