# Generated by Django 5.2 on 2025-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0024_rental_payment_type_service_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='notes3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='notes3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
