# Generated by Django 5.2 on 2025-04-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_vendorcategory_vendor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
