# Generated by Django 5.2 on 2025-05-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0027_rename_category_name_vendorcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('ROS', 'ROS'), ('Drop Load', 'Drop Load'), ('n/a', 'n/a')], default='choose rental type', max_length=100),
        ),
    ]
