# Generated by Django 5.2 on 2025-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_plate_number_alter_vehicle_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rental_status',
            field=models.CharField(choices=[('on_rental', 'On Rental'), ('returned', 'Returned'), ('swapped', 'Swapped')], default='On Rental', max_length=100),
        ),
    ]
