# Generated by Django 5.2 on 2025-05-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0028_alter_rental_rental_type'),
        ('vehicles', '0005_remove_vehicle_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.production'),
        ),
    ]
