# Generated by Django 5.2 on 2025-05-01 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0028_alter_rental_rental_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('start_rental_date', models.DateField()),
                ('end_rental_date', models.DateField()),
                ('contract_number', models.CharField(max_length=100)),
                ('purchase_order', models.CharField(max_length=100)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('misc_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_rental', models.BooleanField(default=False)),
                ('new_swapped', models.BooleanField(default=False)),
                ('notes1', models.CharField(blank=True, max_length=300)),
                ('notes2', models.CharField(blank=True, max_length=300)),
                ('notes3', models.CharField(blank=True, max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.department')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.vendor')),
            ],
        ),
    ]
