# Generated by Django 5.2 on 2025-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
